### ISSUE TITLE
[Feat] 카테고리 이동 구현

### ISSUE THREAD

**Issue by westofsky** [westofsky/fe-newsstand#4]
## ✅ feature 내용
- 언론사가 20초간 보여진 후 자동으로 다음 카테고리로 넘어가게 구현
- 가장 마지막 카테고리가 보여진 후, 처음 카테고리로 이동
- 좌우 화살표를 통해 언론사 이동 구현

## 📝 Todo
- [x] 20초 후 언론사 카테고리 넘어가기 구현
- [x] 가장 마지막 카테고리 보여진 후 처음 카테고리로 이동
- [x] 화살표 클릭시에도 이동할 수 있도록 구현
