### ISSUE TITLE
[Feat] 리스트 뷰 UI 구성

### ISSUE THREAD

**Issue by westofsky** [westofsky/fe-newsstand#6]
## ✅ feature 내용
- 선택된 카테고리 외 다른 카테고리 mouse hover시 밑줄이 생기게 한다.
- 각 카테고리를 누르면 해당 카테고리로 이동하게 한다.
- 언론사 기사 영역에 요소들을 채운다.
- 메인뉴스의 썸네일 이미지에 mouse hover 시 5%확대시키고, 타이틀에 밑줄이 생기게 한다.
- 구독하기 버튼을 누르면 '내가 구독한 언로사에 추가되었습니다.'라는 스낵바를 5초간 유지한 후, 즉시 내가 구독한 언론사 탭의 리스트 보기 화면으로 이동시킨다.

## 📝 Todo
- [x] 카테고리 mouse hover시 밑줄 생기게 하기.
- [x] 각 카테고리 누르면 해당 카테고리로 이동하게 하기
- [x] 언론사 기사 영역에 요소 채우기
- [x] 썸네일 확대시키기
- [x] 구독하기 버튼 누르면 스낵바 표현 후 즉시 리스트 보기 화면으로 이동시키기
