### ISSUE TITLE
[Feat] 언론사 기사 해지

### ISSUE THREAD

**Issue by westofsky** [westofsky/fe-newsstand#7]
## ✅ feature 내용
- [구독해지] 버튼을 누르면 {언론사이름}을 구독해지하시겠습니까? 라는 alert가 뜨도록 한다.

## 📝 Todo
- [x] 구독해지하는 alert 창 디자인
- [x] X버튼을 눌렀을 때, 밑줄이 되도록 진행
- [x] 아니오 누르면 그냥 alert 제거, 해지합니다 하면 구독 목록에서 삭제
- [x] 해지합니다 후 목록의 다음 순서 언론사가 바로 나타나도록 설정
